---
- hosts: webservers
  become: true 
  vars:
    myport: 8080
  tasks:
   - name: Add Jenkins Repo Key
     ansible.builtin.apt_key:
       url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
       state: present
   - name: Adding Jenkins repo
     ansible.builtin.apt_repository:
       repo: deb https://pkg.jenkins.io/debian-stable binary/
       state: present
   - name: Now updating the apt repository
     apt:
       update_cache: yes
   - name: Java Installation
     apt:
       name: default-jre
       state: present
   - name: Jenkins Installation
     apt:
       name: jenkins
       state: present
   - name: Getting Admin password
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     register: adminpassword
   - name: Fetching Server IP address
     shell: curl ifconfig.me
     register: myip
   - name: Generating server URL to open in the browser
     debug:
       msg: 'http://{{ myip.stdout }}:{{ myport}}'
   - name: Displaying Admin Password
     debug:
       msg: '{{ adminpassword.stdout }}'
